SELECT
    TRIM(
        CONCAT(
            COALESCE(c.NAME, ''),
            CASE
                WHEN c.SURNAME IS NULL OR c.SURNAME = '' THEN ''
                ELSE CONCAT(' ', c.SURNAME)
            END
        )
    ) AS client_full_name,
    COALESCE(SUM(CASE WHEN ca.ACCOUNT_TYPE_CODE IN ('PLOAN', 'HLOAN') THEN ca.DISPLAY_BALANCE END), 0) AS loan_balance_aggregate,
    COALESCE(SUM(CASE WHEN at.TRANSACTIONAL = TRUE THEN ca.DISPLAY_BALANCE END), 0) AS transactional_balance_aggregate,
    COALESCE(SUM(CASE WHEN ca.ACCOUNT_TYPE_CODE IN ('PLOAN', 'HLOAN') THEN ca.DISPLAY_BALANCE END), 0)
        + COALESCE(SUM(CASE WHEN at.TRANSACTIONAL = TRUE THEN ca.DISPLAY_BALANCE END), 0) AS net_position
FROM CLIENT c
LEFT JOIN CLIENT_ACCOUNT ca ON ca.CLIENT_ID = c.CLIENT_ID
LEFT JOIN ACCOUNT_TYPE at ON at.ACCOUNT_TYPE_CODE = ca.ACCOUNT_TYPE_CODE
GROUP BY c.CLIENT_ID, c.NAME, c.SURNAME
ORDER BY c.CLIENT_ID;
